
version: "3.9"
   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: "pg_isready --username=postgres && psql --username=postgres --list"
      timeout: 10s
      retries: 20
  newsfeeder:
    build: .
    command: |
      ./newsfeeder
    ports:
      - "30005:30005"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - SERVICE_PORT=30005
    depends_on:
      db:
        condition: service_healthy